"""
Django management command to generate all data visualization charts
"""

import os
from django.core.management.base import BaseCommand
from data_visualization.models import Chart

class Command(BaseCommand):
    help = 'Generate all data visualization charts'

    def handle(self, *args, **options):
        self.stdout.write(self.style.SUCCESS('开始生成数据可视化图表记录...'))

        # 清理旧的图表记录（可选）
        self.stdout.write('清理旧的图表记录...')
        Chart.objects.all().delete()

        # 创建图表记录（暂时使用占位图片）
        charts_data = [
            {
                'title': 'Death Valley Temperatures 2014',
                'description': 'Daily high and low temperatures recorded in Death Valley, California throughout 2014. This chart visualizes the extreme temperature fluctuations characteristic of this desert location.',
                'category': 'Temperature',
                'image_path': '/media/charts/death_valley_temperatures.png',
                'data_file': '/home/ubuntu/Code/Code_Practice/Data_Visuallization/plot_temperatures/death_valley_2014.csv',
                'script_file': 'data_visualization/scripts/temperature_chart.py'
            },
            {
                'title': 'Random Walk Visualization',
                'description': 'A random walk visualization with 5000 points. Starting point is marked in green, ending point in red. The colors indicate the order of steps taken in the random walk process.',
                'category': 'Random Walk',
                'image_path': '/media/charts/random_walk.png',
                'data_file': 'Generated by algorithm',
                'script_file': 'data_visualization/scripts/random_walk_chart.py'
            },
        ]

        for chart_data in charts_data:
            try:
                Chart.objects.create(**chart_data)
                self.stdout.write(self.style.SUCCESS(f'✓ 图表已创建: {chart_data["title"]}'))
            except Exception as e:
                self.stdout.write(self.style.ERROR(f'✗ 图表创建失败 {chart_data["title"]}: {e}'))

        # 显示所有创建的图表
        self.stdout.write('\n图表创建完成！数据库中的图表：')
        charts = Chart.objects.all()
        for chart in charts:
            self.stdout.write(f'  - {chart.title} ({chart.category})')

        self.stdout.write(self.style.SUCCESS(f'\n总计：{charts.count()} 个图表'))
        self.stdout.write(self.style.WARNING('注意：由于虚拟环境中未安装 matplotlib，图表图片需要手动生成或运行原始脚本。'))
