import matplotlib
matplotlib.use('Agg')  # 使用非交互式后端
import matplotlib.pyplot as plt
import os
import sys

# 添加 Data_Visuallization/random_walk 路径到 Python 路径
DATA_DIR = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(__file__))), 'Code_Practice', 'Data_Visuallization', 'random_walk')
sys.path.append(DATA_DIR)

from random_walk import Randomwalk

# 设置图表保存目录
CHART_DIR = os.path.join(os.path.dirname(os.path.dirname(__file__)), 'media', 'charts')

def ensure_chart_dir():
    """确保图表目录存在"""
    if not os.path.exists(CHART_DIR):
        os.makedirs(CHART_DIR)

def generate_random_walk_chart():
    """生成随机漫步图表"""
    ensure_chart_dir()

    output_path = os.path.join(CHART_DIR, 'random_walk.png')

    # 创建一个 RandomWalk 实例
    rw = Randomwalk(5000)
    rw.fill_walk()

    # 设置绘图窗口的尺寸
    plt.figure(dpi=128, figsize=(10, 6))

    point_numbers = list(range(rw.num_points))
    plt.scatter(rw.x_values, rw.y_values, c=point_numbers, cmap=plt.cm.Blues, edgecolors='none', s=1)

    # 突出起点和终点
    plt.scatter(0, 0, c='green', edgecolors='none', s=100)
    plt.scatter(rw.x_values[-1], rw.y_values[-1], c='red', edgecolors='none', s=100)

    # 隐藏坐标轴
    plt.axis('off')

    # 保存图表
    plt.savefig(output_path, bbox_inches='tight', dpi=128)
    plt.close()

    return {
        'title': 'Random Walk Visualization',
        'description': 'A random walk visualization with 5000 points. Starting point is marked in green, ending point in red. The colors indicate the order of steps taken in the random walk process.',
        'category': 'Random Walk',
        'image_path': f'/media/charts/random_walk.png',
        'data_file': 'Generated by algorithm',
        'script_file': 'data_visualization/scripts/random_walk_chart.py'
    }

if __name__ == '__main__':
    chart_info = generate_random_walk_chart()
    print(f"Chart generated: {chart_info['image_path']}")
    print(f"Title: {chart_info['title']}")
